version: '3.9'
services:
  backend:
    container_name: backend
    build: .
    ports:
      - 8000:3000
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    container_name: postgres-db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres # always postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=12345
    ports:
      - '5432:5432'
    volumes:
      - ./docker/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
networks:
  chat-network:
    driver: bridge
